server:
  port: 6081
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lightmin-client
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/sampleDB
    username: root
    password: db2admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch: 
    initialize-schema: never
    job:
      enabled: false

    lightmin:
      batch:
        repository-type: jdbc
        data-source-name: dataSourceCommon
        table-prefix: "BATCH_"
      client:
        classic:
          period: 86400000  # 하루 주기로 서버에 상태 등록
          register-once: true
          auto-deregistration: false
          server:
            url: http://localhost:6080/lightadmin
      repository:
        jdbc: 
          data-source-name: dataSourceCommon
        remote:
          server-url: http://localhost:6080/lightadmin

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.tuxdevelop: INFO