
/**********************************************
Dataflow 데이터베이스[배치관리서버용] 테이블
**********************************************/

-- ============================================
-- Spring Cloud Data Flow 2.11.5 Schema for MySQL 5.7
-- ============================================

CREATE TABLE IF NOT EXISTS HIBERNATE_SEQUENCE (
    NEXT_VAL BIGINT
) ;

INSERT INTO HIBERNATE_SEQUENCE VALUES (1);

CREATE TABLE IF NOT EXISTS APP_REGISTRATION (
    ID BIGINT NOT NULL PRIMARY KEY,
    OBJECT_VERSION BIGINT,
    DEFAULT_VERSION BIT(1),
    METADATA_URI TEXT,
    NAME VARCHAR(255),
    TYPE INT,
    URI TEXT,
    VERSION VARCHAR(255),
    BOOT_VERSION VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS AUDIT_RECORDS (
    ID BIGINT NOT NULL PRIMARY KEY,
    AUDIT_ACTION BIGINT,
    AUDIT_DATA LONGTEXT,
    AUDIT_OPERATION BIGINT,
    CORRELATION_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    CREATED_ON DATETIME,
    PLATFORM_NAME VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS STREAM_DEFINITIONS (
    DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    DEFINITION TEXT,
    DESCRIPTION VARCHAR(255),
    ORIGINAL_DEFINITION TEXT
) ;

CREATE TABLE IF NOT EXISTS TASK_DEFINITIONS (
    DEFINITION_NAME VARCHAR(255) NOT NULL PRIMARY KEY,
    DEFINITION TEXT,
    DESCRIPTION VARCHAR(255)
) ;

CREATE TABLE IF NOT EXISTS TASK_DEPLOYMENT (
    ID BIGINT NOT NULL PRIMARY KEY,
    OBJECT_VERSION BIGINT,
    TASK_DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    TASK_DEFINITION_NAME VARCHAR(255) NOT NULL,
    PLATFORM_NAME VARCHAR(255) NOT NULL,
    CREATED_ON DATETIME,
    CONSTRAINT TASK_DEPLOYMENT_UK UNIQUE (TASK_DEPLOYMENT_ID)
) ;

CREATE TABLE IF NOT EXISTS TASK_EXECUTION_METADATA (
    ID BIGINT NOT NULL PRIMARY KEY,
    TASK_EXECUTION_ID BIGINT NOT NULL,
    TASK_EXECUTION_MANIFEST TEXT,
    CONSTRAINT TASK_METADATA_FK FOREIGN KEY (TASK_EXECUTION_ID)
        REFERENCES TASK_EXECUTION(TASK_EXECUTION_ID) ON DELETE CASCADE
) ;

CREATE TABLE IF NOT EXISTS TASK_EXECUTION_METADATA_SEQ (
    ID BIGINT NOT NULL,
    UNIQUE_KEY CHAR(1) NOT NULL,
    CONSTRAINT UNIQUE_KEY_UN UNIQUE (UNIQUE_KEY)
) ;

INSERT INTO TASK_EXECUTION_METADATA_SEQ (ID, UNIQUE_KEY) SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS TMP WHERE NOT EXISTS(SELECT * FROM TASK_EXECUTION_METADATA_SEQ);

CREATE TABLE IF NOT EXISTS SCHEMA_VERSION (
    VERSION_RANK INT NOT NULL,
    INSTALLED_RANK INT NOT NULL,
    VERSION VARCHAR(50) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(200) NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    SCRIPT VARCHAR(1000) NOT NULL,
    CHECKSUM INT,
    INSTALLED_BY VARCHAR(100) NOT NULL,
    INSTALLED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXECUTION_TIME INT NOT NULL,
    SUCCESS BIT(1) NOT NULL,
    INDEX SCHEMA_VERSION_IR_IDX (INSTALLED_RANK),
    INDEX SCHEMA_VERSION_S_IDX (SUCCESS)
) ;

